name: Main Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

#env:
  # KUBE_CONTEXT: upme2/6g:personal
  # KUBE_CONTEXT: upme2/6g:upme

jobs:
  # databases:
  #   uses: ./.github/workflows/databases.yml

  # secrets:
  #   uses: ./.github/workflows/secrets.yml

  deploy:
    uses: ./.github/workflows/runner.yml